# Generated by Django 4.2.26 on 2025-11-05 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appTravel', '0002_imagen_alter_pais_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagen',
            options={'verbose_name_plural': 'Imagenes'},
        ),
        migrations.AddField(
            model_name='imagen',
            name='oferta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='galeria', to='appTravel.oferta'),
        ),
        migrations.AlterField(
            model_name='imagen',
            name='titulo',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
