# Generated by Django 5.2.7 on 2025-11-07 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTravel', '0003_alter_imagen_options_imagen_oferta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='icono',
            field=models.ImageField(blank=True, null=True, upload_to='iconos_categorias/'),
        ),
    ]
