# Generated by Django 5.2.7 on 2025-11-07 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTravel', '0004_categoria_icono'),
    ]

    operations = [
        migrations.AddField(
            model_name='pais',
            name='icono',
            field=models.ImageField(blank=True, null=True, upload_to='iconos_paises/'),
        ),
    ]
