# Generated by Django 5.2.7 on 2025-11-25 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTravel', '0005_pais_icono'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservaInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_viaje_preferida', models.DateField()),
                ('numero_personas', models.PositiveIntegerField(default=1)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='appTravel.oferta', verbose_name='Oferta')),
            ],
            options={
                'verbose_name': 'Solicitud de Reserva',
                'verbose_name_plural': 'Solicitudes de Reserva',
            },
        ),
    ]
